
snowflake:
  outputs:

    dev: 
      type: snowflake
      account: dqa16210
      user: DBT_CLOUD_DEV
      password: Sham*12345
      role: TRANSFORMER_DEV
      database: DEV
      warehouse: TRANSFORMING
      schema: public
      threads: 2
      client_session_keep_alive: False

  target: dev